services:  
  # Database service definition
  db:
    image: postgres:16-alpine             # Use the lightweight Alpine Linux version of PostgreSQL 16
    container_name: ${DB_NAME}_container
    restart: always  
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  # FastAPI Backend service definition
  backend:
    build: ./backend
    container_name: smartstock_backend
    command: >
      sh -c "alembic upgrade head && 
             uvicorn app.main:app --host 0.0.0.0 --port 8000"
    # command: tail -f /dev/null
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - db

# Define the named volumes used in the services section
volumes:
  # This volume ensures data persists even if the container is removed
  postgres_data: