"""First migration

Revision ID: c36177fa7035
Revises: 
Create Date: 2026-03-11 05:09:19.053671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c36177fa7035'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('category_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('supplier_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('tax_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('supplier_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bank_account_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('logo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='supplierstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_code')
    )
    op.create_table('units',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('unit_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('unit_symbol', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('hash_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('manager', 'staff', name='userrole'), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', name='userstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('ocr_raw_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('invoice_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('invoice_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('sub_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_tax', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_status', sa.Enum('unpaid', 'partially_paid', 'paid', 'refunded', name='paymentstatus'), nullable=False),
    sa.Column('invoice_status', sa.Enum('pending', 'processing', 'completed', 'error', name='invoicestatus'), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('base_unit_id', sa.Uuid(), nullable=True),
    sa.Column('sku_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('barcode', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('product_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('stock_quantity', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('sales_volume', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('last_unit_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('status', sa.Enum('in_stock', 'out_of_stock', 'low_stock', 'discontinued', name='productstatus'), nullable=False),
    sa.Column('warehouse_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_batch_tracked', sa.Boolean(), nullable=False),
    sa.Column('batch_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['base_unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('product_code'),
    sa.UniqueConstraint('sku_code')
    )
    op.create_table('invoice_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('raw_product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('has_gst', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_unit_conversions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('factor', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('transaction_type', sa.Enum('import_type', 'export_type', 'inventory_check', 'adjustment', name='transactiontype'), nullable=False),
    sa.Column('quantity_change', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_log')
    op.drop_table('product_unit_conversions')
    op.drop_table('invoice_items')
    op.drop_table('products')
    op.drop_table('invoices')
    op.drop_table('users')
    op.drop_table('units')
    op.drop_table('suppliers')
    op.drop_table('categories')
    # ### end Alembic commands ###
